use std::fmt::Display;

#[derive(PartialEq, Eq, Debug, Clone, Hash)]
pub enum TokenKind {
    // Control flow
    If,
    Else,
    Loop,
    Return,

    True,
    False,

    // Enums/pattern matching
    Enum,
    Case,
    Match,
    Underscore,

    // More
    QuestionMark,
    Arrow,
    Colon,
    Newline,
    Dot,
    Plus,
    Minus,
    Slash,
    Star,
    Equals,
    Bang,
    Less,
    LessEquals,
    Greater,
    GreaterEquals,
    Tilde,
    PlusEquals,
    MinusEquals,
    StarEquals,
    SlashEquals,
    EqualsEquals,
    BangEquals,
    TildeEquals,
    Caret,
    CaretEquals,
    Pipe,
    PipePipe,
    Amp,
    AmpEquals,
    LeftBrace,
    RightBrace,
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    Comma,
    Struct,
    Int(String),
    Float(String),
    Identifier(String),
    Func,
    Let,
    EOF,
    Generated,
}

impl Display for TokenKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{self:?}")
    }
}

impl TokenKind {
    pub fn as_str(&self) -> String {
        match &self {
            TokenKind::If => "if",
            TokenKind::Else => "else",
            TokenKind::Loop => "loop",
            TokenKind::Return => "return",
            TokenKind::True => "true",
            TokenKind::False => "false",
            TokenKind::Enum => "enum",
            TokenKind::Case => "case",
            TokenKind::Match => "match",
            TokenKind::Underscore => "_",
            TokenKind::QuestionMark => "?",
            TokenKind::Arrow => "->",
            TokenKind::Colon => ":",
            TokenKind::Newline => "\n",
            TokenKind::Dot => ".",
            TokenKind::Plus => "+",
            TokenKind::Minus => "-",
            TokenKind::Slash => "/",
            TokenKind::Star => "*",
            TokenKind::Equals => "=",
            TokenKind::Bang => "!",
            TokenKind::Less => "<",
            TokenKind::LessEquals => "<=",
            TokenKind::Greater => ">",
            TokenKind::GreaterEquals => ">=",
            TokenKind::Tilde => "~",
            TokenKind::PlusEquals => "+=",
            TokenKind::MinusEquals => "-=",
            TokenKind::StarEquals => "*=",
            TokenKind::SlashEquals => "/=",
            TokenKind::EqualsEquals => "==",
            TokenKind::BangEquals => "!=",
            TokenKind::TildeEquals => "~=",
            TokenKind::Caret => "^",
            TokenKind::CaretEquals => "^=",
            TokenKind::Pipe => "|",
            TokenKind::PipePipe => "||",
            TokenKind::Amp => "&",
            TokenKind::AmpEquals => "&=",
            TokenKind::LeftBrace => "{",
            TokenKind::RightBrace => "}",
            TokenKind::LeftParen => "(",
            TokenKind::RightParen => ")",
            TokenKind::LeftBracket => "[",
            TokenKind::RightBracket => "]",
            TokenKind::Comma => ",",
            TokenKind::Struct => "struct",
            TokenKind::Int(val) => &val,
            TokenKind::Float(val) => &val,
            TokenKind::Identifier(ident) => &ident,
            TokenKind::Func => "func",
            TokenKind::Let => "let",
            TokenKind::EOF => "EOF",
            TokenKind::Generated => "(generated)",
        }
        .to_string()
    }
}
