[package]
name = "talk-llvm"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
talk = { path = "..", default-features = false }
talk-mir = { path = "../talk-mir" }
talk-native-runtime = { path = "../talk-native-runtime" }

[dev-dependencies]
talk-vm = { path = "../talk-vm" }
talk-mir = { path = "../talk-mir" }

[lints.clippy]
approx_constant = "allow"
