[package]
name = "talk-vm"
version = "0.1.0"
edition = "2024"

[dependencies]
rustc-hash = "2.1.1"
profiling = { version = "1.0.18", default-features = false }
tracy-client = { version = "0.18.4", default-features = false, features = ["timer-fallback"], optional = true }

[features]
profile-tracy = ["dep:tracy-client", "profiling/profile-with-tracy"]

[target.'cfg(unix)'.dependencies]
libc = "0.2"

[lints.clippy]
approx_constant = "allow"
