use crate::token_kind::TokenKind;

pub(super) fn handle(string: &str) -> TokenKind {
    use TokenKind::*;
    match string {
        "any" => Any,
        "as" => As,
        "func" => Func,
        "let" => Let,
        "if" => If,
        "else" => Else,
        "true" => True,
        "false" => False,
        "loop" => Loop,
        "enum" => Enum,
        "case" => Case,
        "match" => Match,
        "return" => Return,
        "struct" => Struct,
        "extend" => Extend,
        "break" => Break,
        "init" => Init,
        "protocol" => Protocol,
        "import" => Import,
        "use" => Use,
        "public" => Public,
        "linear" => Linear,
        "static" => Static,
        "associated" => Associated,
        "typealias" => Typealias,
        "effect" => Effect,
        "handling" => Handling,
        "in" => In,
        "continue" => Continue,
        "mut" => Mut,
        "consuming" => Consuming,
        "for" => For,
        _ => Identifier,
    }
}
