use std::fmt::Display;

#[derive(PartialEq, Eq, Debug, Clone, Hash)]
pub enum TokenKind {
    LineComment(String),

    Import,

    // Effects
    Effect,
    Handling,
    EffectName(String),
    SingleQuote,

    // Control flow
    If,
    Else,
    Loop,
    Return,

    True,
    False,

    // Enums/pattern matching
    Enum,
    Case,
    Match,
    Underscore,

    Protocol,
    Associated,
    Typealias,

    // More
    As,
    At,
    Extend,
    QuestionMark,
    Semicolon,
    Arrow,
    Colon,
    Newline,
    Dot,
    Plus,
    Minus,
    Slash,
    Star,
    Equals,
    Bang,
    Less,
    LessEquals,
    Greater,
    GreaterEquals,
    Tilde,
    PlusEquals,
    MinusEquals,
    StarEquals,
    SlashEquals,
    EqualsEquals,
    BangEquals,
    TildeEquals,
    Caret,
    CaretEquals,
    Pipe,
    PipePipe,
    Amp,
    AmpAmp,
    AmpEquals,
    LeftBrace,
    RightBrace,
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    Percent,
    Comma,
    Struct,
    Static,
    Break,
    Int(String),
    Float(String),
    Identifier(String),
    StringLiteral(String),
    Attribute(String),
    Func,
    Init,
    In,
    Let,
    Mut,
    EOF,
    Generated,
    DotDot,
    DotDotDot,
    IRRegister(String),
    BoundVar(String),
    Dollar,
}

impl Display for TokenKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl TokenKind {
    pub fn as_str(&self) -> String {
        let text = match &self {
            TokenKind::EffectName(v) => &format!("'{v}"),
            TokenKind::Dollar => "$",
            TokenKind::BoundVar(v) => &format!("${v}"),
            TokenKind::Percent => "%",
            TokenKind::IRRegister(v) => &format!("%{v}"),
            TokenKind::As => "as",
            TokenKind::Attribute(attr) => &format!("@{attr}"),
            TokenKind::Typealias => "typealias",
            TokenKind::LineComment(text) => &format!("// {text}"),
            TokenKind::If => "if",
            TokenKind::Associated => "associated",
            TokenKind::Else => "else",
            TokenKind::Loop => "loop",
            TokenKind::Return => "return",
            TokenKind::True => "true",
            TokenKind::False => "false",
            TokenKind::Enum => "enum",
            TokenKind::Case => "case",
            TokenKind::Match => "match",
            TokenKind::Underscore => "_",
            TokenKind::QuestionMark => "?",
            TokenKind::Arrow => "->",
            TokenKind::Colon => ":",
            TokenKind::Newline => "\n",
            TokenKind::Dot => ".",
            TokenKind::Plus => "+",
            TokenKind::Minus => "-",
            TokenKind::Slash => "/",
            TokenKind::Star => "*",
            TokenKind::Equals => "=",
            TokenKind::Bang => "!",
            TokenKind::Less => "<",
            TokenKind::LessEquals => "<=",
            TokenKind::Greater => ">",
            TokenKind::GreaterEquals => ">=",
            TokenKind::Tilde => "~",
            TokenKind::PlusEquals => "+=",
            TokenKind::MinusEquals => "-=",
            TokenKind::StarEquals => "*=",
            TokenKind::SlashEquals => "/=",
            TokenKind::EqualsEquals => "==",
            TokenKind::BangEquals => "!=",
            TokenKind::TildeEquals => "~=",
            TokenKind::Caret => "^",
            TokenKind::CaretEquals => "^=",
            TokenKind::Pipe => "|",
            TokenKind::PipePipe => "||",
            TokenKind::Amp => "&",
            TokenKind::AmpAmp => "&&",
            TokenKind::AmpEquals => "&=",
            TokenKind::LeftBrace => "{",
            TokenKind::RightBrace => "}",
            TokenKind::LeftParen => "(",
            TokenKind::RightParen => ")",
            TokenKind::LeftBracket => "[",
            TokenKind::RightBracket => "]",
            TokenKind::Comma => ",",
            TokenKind::Struct => "struct",
            TokenKind::Int(val) => val,
            TokenKind::Float(val) => val,
            TokenKind::Identifier(ident) => ident,
            TokenKind::Func => "func",
            TokenKind::Let => "let",
            TokenKind::Mut => "mut",
            TokenKind::EOF => "EOF",
            TokenKind::Generated => "(generated)",
            TokenKind::Init => "init",
            TokenKind::Break => "break",
            TokenKind::Protocol => "protocol",
            TokenKind::Semicolon => ";",
            TokenKind::StringLiteral(string) => &format!("\"{string}\""),
            TokenKind::Extend => "extend",
            TokenKind::Import => "import",
            TokenKind::Static => "static",
            TokenKind::At => "@",
            TokenKind::DotDot => "..",
            TokenKind::DotDotDot => "...",
            TokenKind::Effect => "effect",
            TokenKind::Handling => "handling",
            TokenKind::In => "in",
            TokenKind::SingleQuote => "'",
        };

        text.to_string()
    }
}
