use std::fmt::Display;

#[derive(PartialEq, Eq, Debug, Clone, Copy, Hash)]
pub enum TokenKind {
    LineComment,

    Import,
    Public,

    // Effects
    Effect,
    Handling,
    EffectName,
    SingleQuote,

    // Control flow
    If,
    Else,
    Loop,
    For,
    Return,
    Continue,

    True,
    False,

    // Enums/pattern matching
    Enum,
    Case,
    Match,
    Underscore,

    Protocol,
    Associated,
    Typealias,

    // More
    As,
    At,
    Extend,
    QuestionMark,
    Semicolon,
    Arrow,
    Colon,
    Newline,
    Dot,
    Plus,
    Minus,
    Slash,
    Star,
    Equals,
    Bang,
    Less,
    LessEquals,
    Greater,
    GreaterEquals,
    Tilde,
    PlusEquals,
    MinusEquals,
    StarEquals,
    SlashEquals,
    EqualsEquals,
    BangEquals,
    TildeEquals,
    Caret,
    CaretEquals,
    Pipe,
    PipePipe,
    Amp,
    AmpAmp,
    AmpEquals,
    LeftBrace,
    RightBrace,
    LeftParen,
    RightParen,
    LeftBracket,
    RightBracket,
    Percent,
    Comma,
    Struct,
    Static,
    Break,
    Int,
    Float,
    Identifier,
    StringLiteral,
    Attribute,
    Func,
    Init,
    In,
    Let,
    Mut,
    EOF,
    Generated,
    DotDot,
    DotDotDot,
    IRRegister,
    BoundVar,
    Dollar,
}

impl Display for TokenKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl TokenKind {
    pub fn as_str(&self) -> &'static str {
        match self {
            TokenKind::Continue => "continue",
            TokenKind::EffectName => "'<effect>",
            TokenKind::Dollar => "$",
            TokenKind::BoundVar => "$<var>",
            TokenKind::Percent => "%",
            TokenKind::IRRegister => "%<reg>",
            TokenKind::As => "as",
            TokenKind::Attribute => "@<attr>",
            TokenKind::Typealias => "typealias",
            TokenKind::LineComment => "// <comment>",
            TokenKind::If => "if",
            TokenKind::Associated => "associated",
            TokenKind::Else => "else",
            TokenKind::Loop => "loop",
            TokenKind::For => "for",
            TokenKind::Return => "return",
            TokenKind::True => "true",
            TokenKind::False => "false",
            TokenKind::Enum => "enum",
            TokenKind::Case => "case",
            TokenKind::Match => "match",
            TokenKind::Underscore => "_",
            TokenKind::QuestionMark => "?",
            TokenKind::Arrow => "->",
            TokenKind::Colon => ":",
            TokenKind::Newline => "\n",
            TokenKind::Dot => ".",
            TokenKind::Plus => "+",
            TokenKind::Minus => "-",
            TokenKind::Slash => "/",
            TokenKind::Star => "*",
            TokenKind::Equals => "=",
            TokenKind::Bang => "!",
            TokenKind::Less => "<",
            TokenKind::LessEquals => "<=",
            TokenKind::Greater => ">",
            TokenKind::GreaterEquals => ">=",
            TokenKind::Tilde => "~",
            TokenKind::PlusEquals => "+=",
            TokenKind::MinusEquals => "-=",
            TokenKind::StarEquals => "*=",
            TokenKind::SlashEquals => "/=",
            TokenKind::EqualsEquals => "==",
            TokenKind::BangEquals => "!=",
            TokenKind::TildeEquals => "~=",
            TokenKind::Caret => "^",
            TokenKind::CaretEquals => "^=",
            TokenKind::Pipe => "|",
            TokenKind::PipePipe => "||",
            TokenKind::Amp => "&",
            TokenKind::AmpAmp => "&&",
            TokenKind::AmpEquals => "&=",
            TokenKind::LeftBrace => "{",
            TokenKind::RightBrace => "}",
            TokenKind::LeftParen => "(",
            TokenKind::RightParen => ")",
            TokenKind::LeftBracket => "[",
            TokenKind::RightBracket => "]",
            TokenKind::Comma => ",",
            TokenKind::Struct => "struct",
            TokenKind::Int => "<int>",
            TokenKind::Float => "<float>",
            TokenKind::Identifier => "<ident>",
            TokenKind::Func => "func",
            TokenKind::Let => "let",
            TokenKind::Mut => "mut",
            TokenKind::EOF => "EOF",
            TokenKind::Generated => "(generated)",
            TokenKind::Init => "init",
            TokenKind::Break => "break",
            TokenKind::Protocol => "protocol",
            TokenKind::Semicolon => ";",
            TokenKind::StringLiteral => "\"<string>\"",
            TokenKind::Extend => "extend",
            TokenKind::Import => "import",
            TokenKind::Public => "public",
            TokenKind::Static => "static",
            TokenKind::At => "@",
            TokenKind::DotDot => "..",
            TokenKind::DotDotDot => "...",
            TokenKind::Effect => "effect",
            TokenKind::Handling => "handling",
            TokenKind::In => "in",
            TokenKind::SingleQuote => "'",
        }
    }
}
