package talkex:host;

world host {
   record highlight-token {
    kind:  string,
    start: u32,
    end:   u32,
  }

  record IO {
    stdout: list<u8>,
    stderr: list<u8>
  }

  record runner {
    id: u8
  }

  export highlight: func(code: string) -> list<highlight-token>;
  export ir: func(code: string) -> string;
  export run: func(code: string) -> IO;
  export ping: func() -> IO;
}
