package talkex:host;

interface types {
  record highlight-token {
    kind:  string,
    start: u32,
    end:   u32,
  }

  resource runner {
    constructor();
    highlight: func(code: string) -> list<highlight-token>;
    ir: func(code: string) -> string;
    run: func(code: string);
    ping: func();
  }
}

world host {
  export types;
}
