// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[derive(Clone)]
pub struct HighlightToken {
    pub kind: _rt::String,
    pub start: u32,
    pub end: u32,
}
impl ::core::fmt::Debug for HighlightToken {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("HighlightToken")
            .field("kind", &self.kind)
            .field("start", &self.start)
            .field("end", &self.end)
            .finish()
    }
}
#[derive(Clone)]
pub struct Io {
    pub stdout: _rt::Vec<u8>,
    pub stderr: _rt::Vec<u8>,
}
impl ::core::fmt::Debug for Io {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.debug_struct("Io")
            .field("stdout", &self.stdout)
            .field("stderr", &self.stderr)
            .finish()
    }
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_highlight_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::highlight(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec5 = result1;
    let len5 = vec5.len();
    let layout5 = _rt::alloc::Layout::from_size_align_unchecked(
        vec5.len() * (8 + 2 * ::core::mem::size_of::<*const u8>()),
        ::core::mem::size_of::<*const u8>(),
    );
    let result5 = if layout5.size() != 0 {
        let ptr = _rt::alloc::alloc(layout5).cast::<u8>();
        if ptr.is_null() {
            _rt::alloc::handle_alloc_error(layout5);
        }
        ptr
    } else {
        ::core::ptr::null_mut()
    };
    for (i, e) in vec5.into_iter().enumerate() {
        let base = result5.add(i * (8 + 2 * ::core::mem::size_of::<*const u8>()));
        {
            let HighlightToken { kind: kind3, start: start3, end: end3 } = e;
            let vec4 = (kind3.into_bytes()).into_boxed_slice();
            let ptr4 = vec4.as_ptr().cast::<u8>();
            let len4 = vec4.len();
            ::core::mem::forget(vec4);
            *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
            *base.add(0).cast::<*mut u8>() = ptr4.cast_mut();
            *base.add(2 * ::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(
                start3,
            );
            *base.add(4 + 2 * ::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(
                end3,
            );
        }
    }
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
    *ptr2.add(0).cast::<*mut u8>() = result5;
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_highlight<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    let base4 = l0;
    let len4 = l1;
    for i in 0..len4 {
        let base = base4.add(i * (8 + 2 * ::core::mem::size_of::<*const u8>()));
        {
            let l2 = *base.add(0).cast::<*mut u8>();
            let l3 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l2, l3, 1);
        }
    }
    _rt::cabi_dealloc(
        base4,
        len4 * (8 + 2 * ::core::mem::size_of::<*const u8>()),
        ::core::mem::size_of::<*const u8>(),
    );
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_ir_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::ir(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    let vec3 = (result1.into_bytes()).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr2.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_ir<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    _rt::cabi_dealloc(l0, l1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_run_cabi<T: Guest>(arg0: *mut u8, arg1: usize) -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let len0 = arg1;
    let bytes0 = _rt::Vec::from_raw_parts(arg0.cast(), len0, len0);
    let result1 = T::run(_rt::string_lift(bytes0));
    let ptr2 = (&raw mut _RET_AREA.0).cast::<u8>();
    let Io { stdout: stdout3, stderr: stderr3 } = result1;
    let vec4 = (stdout3).into_boxed_slice();
    let ptr4 = vec4.as_ptr().cast::<u8>();
    let len4 = vec4.len();
    ::core::mem::forget(vec4);
    *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
    *ptr2.add(0).cast::<*mut u8>() = ptr4.cast_mut();
    let vec5 = (stderr3).into_boxed_slice();
    let ptr5 = vec5.as_ptr().cast::<u8>();
    let len5 = vec5.len();
    ::core::mem::forget(vec5);
    *ptr2.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
    *ptr2.add(2 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr5
        .cast_mut();
    ptr2
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_run<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    let base2 = l0;
    let len2 = l1;
    _rt::cabi_dealloc(base2, len2 * 1, 1);
    let l3 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l4 = *arg0.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let base5 = l3;
    let len5 = l4;
    _rt::cabi_dealloc(base5, len5 * 1, 1);
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn _export_ping_cabi<T: Guest>() -> *mut u8 {
    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
    let result0 = T::ping();
    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
    let Io { stdout: stdout2, stderr: stderr2 } = result0;
    let vec3 = (stdout2).into_boxed_slice();
    let ptr3 = vec3.as_ptr().cast::<u8>();
    let len3 = vec3.len();
    ::core::mem::forget(vec3);
    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
    *ptr1.add(0).cast::<*mut u8>() = ptr3.cast_mut();
    let vec4 = (stderr2).into_boxed_slice();
    let ptr4 = vec4.as_ptr().cast::<u8>();
    let len4 = vec4.len();
    ::core::mem::forget(vec4);
    *ptr1.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
    *ptr1.add(2 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4
        .cast_mut();
    ptr1
}
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_ping<T: Guest>(arg0: *mut u8) {
    let l0 = *arg0.add(0).cast::<*mut u8>();
    let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
    let base2 = l0;
    let len2 = l1;
    _rt::cabi_dealloc(base2, len2 * 1, 1);
    let l3 = *arg0.add(2 * ::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
    let l4 = *arg0.add(3 * ::core::mem::size_of::<*const u8>()).cast::<usize>();
    let base5 = l3;
    let len5 = l4;
    _rt::cabi_dealloc(base5, len5 * 1, 1);
}
pub trait Guest {
    fn highlight(code: _rt::String) -> _rt::Vec<HighlightToken>;
    fn ir(code: _rt::String) -> _rt::String;
    fn run(code: _rt::String) -> Io;
    fn ping() -> Io;
}
#[doc(hidden)]
macro_rules! __export_world_host_cabi {
    ($ty:ident with_types_in $($path_to_types:tt)*) => {
        const _ : () = { #[unsafe (export_name = "highlight")] unsafe extern "C" fn
        export_highlight(arg0 : * mut u8, arg1 : usize,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_highlight_cabi::<$ty > (arg0, arg1) } } #[unsafe
        (export_name = "cabi_post_highlight")] unsafe extern "C" fn
        _post_return_highlight(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_highlight::<$ty > (arg0) } } #[unsafe (export_name = "ir")] unsafe
        extern "C" fn export_ir(arg0 : * mut u8, arg1 : usize,) -> * mut u8 { unsafe {
        $($path_to_types)*:: _export_ir_cabi::<$ty > (arg0, arg1) } } #[unsafe
        (export_name = "cabi_post_ir")] unsafe extern "C" fn _post_return_ir(arg0 : * mut
        u8,) { unsafe { $($path_to_types)*:: __post_return_ir::<$ty > (arg0) } } #[unsafe
        (export_name = "run")] unsafe extern "C" fn export_run(arg0 : * mut u8, arg1 :
        usize,) -> * mut u8 { unsafe { $($path_to_types)*:: _export_run_cabi::<$ty >
        (arg0, arg1) } } #[unsafe (export_name = "cabi_post_run")] unsafe extern "C" fn
        _post_return_run(arg0 : * mut u8,) { unsafe { $($path_to_types)*::
        __post_return_run::<$ty > (arg0) } } #[unsafe (export_name = "ping")] unsafe
        extern "C" fn export_ping() -> * mut u8 { unsafe { $($path_to_types)*::
        _export_ping_cabi::<$ty > () } } #[unsafe (export_name = "cabi_post_ping")]
        unsafe extern "C" fn _post_return_ping(arg0 : * mut u8,) { unsafe {
        $($path_to_types)*:: __post_return_ping::<$ty > (arg0) } } };
    };
}
#[doc(hidden)]
pub(crate) use __export_world_host_cabi;
#[cfg_attr(target_pointer_width = "64", repr(align(8)))]
#[cfg_attr(target_pointer_width = "32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit<u8>; 4 * ::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea(
    [::core::mem::MaybeUninit::uninit(); 4 * ::core::mem::size_of::<*const u8>()],
);
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
        if cfg!(debug_assertions) {
            String::from_utf8(bytes).unwrap()
        } else {
            String::from_utf8_unchecked(bytes)
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub use alloc_crate::alloc;
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_host_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*:: __export_world_host_cabi!($ty with_types_in
        $($path_to_types_root)*);
    };
}
#[doc(inline)]
pub(crate) use __export_host_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:talkex:host:host:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 320] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xc5\x01\x01A\x02\x01\
A\x10\x01r\x03\x04kinds\x05starty\x03endy\x03\0\x0fhighlight-token\x03\0\0\x01p}\
\x01r\x02\x06stdout\x02\x06stderr\x02\x03\0\x02IO\x03\0\x03\x01r\x01\x02id}\x03\0\
\x06runner\x03\0\x05\x01p\x01\x01@\x01\x04codes\0\x07\x04\0\x09highlight\x01\x08\
\x01@\x01\x04codes\0s\x04\0\x02ir\x01\x09\x01@\x01\x04codes\0\x04\x04\0\x03run\x01\
\x0a\x01@\0\0\x04\x04\0\x04ping\x01\x0b\x04\0\x10talkex:host/host\x04\0\x0b\x0a\x01\
\0\x04host\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070\
.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
